---
pool: 'Default'

trigger:
  - pravin-test

stages:
  - stage: 'build'
    displayName: 'CI'
    jobs:
      - job: 'maven'
        displayName: 'mvn_build'
        steps:
          - script: |
              java -version
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
              PATH: $(JAVA_HOME_11_X64)/bin;$(PATH)
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.11'
