---
pool: 
  name: 'Default'
  demands:
    - Agent.Name -equals Agent-Linux-2

trigger:
  - pravin-test

stages:
  - stage: 'BuildStage'
    displayName: 'CI'
    jobs:
      - job: 'MavenJob'
        displayName: 'mvn_Build'
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'
