---
pool: 'Default'

trigger:
  - pravin-test

stages:
  - stage: 'build_stage'
    displayName: 'CI'
    jobs:
      - job: 'maven-job'
        displayName: 'mvn_build'
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'
